#DataBase
use data_analysis;


#01. what is total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as Revenue
from mytable
group by gender;


#02. Which Customer Used a Discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from mytable
where discount_applied = "Yes"
and purchase_amount > (select avg(purchase_amount) from mytable)
limit 20;


#03. which are the top 5 products the higer average review rating?
select item_purchased, ROUND(avg(review_rating)) as avg_rating
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;


#04. Compare the average purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount) as Total_revenue
from mytable
group by shipping_type
having shipping_type in ("Standard", "Express");


#05. Do subscribed customer spend more? compare average spend and total revenue between subscriber and non-subscriber  
select sum(purchase_amount) as Total_rev,
	avg(purchase_amount) as Avg_purchase, 
    subscription_status,
    count(customer_id) as Customers
from mytable
group by subscription_status;


#06. which 5 products have the highest percentage of purchase with discount applied
select item_purchased, 
	count(item_purchased) as Items, 
    discount_applied
from mytable
where discount_applied = "Yes"
group by item_purchased
order by count(item_purchased) desc
limit 5;

-- ------------------------With Percentage -------------------------
SELECT 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discount_count,
    COUNT(*) AS total_count,
    (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)) AS discount_percentage
FROM mytable
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


#08. What are the top 3 purchased products in each category
select category,
		item_purchased,
        total_sales,
        rnk
from (
	select category,
		item_purchased,
		count(item_purchased) as total_sales,
		rank()over(partition by category
					order by count(item_purchased)) as rnk
	from mytable
	group by item_purchased, category) t
where rnk <= 3;


#09. Are customers who are repeat buyers (More than 5 previous purchases) are likely to subscribe?
select subscription_status,
	count(customer_id) as customers
from mytable
where previous_purchases > 5
group by subscription_status;


#10. what is the revenue contributed by each age group?
select sum(purchase_amount) as Revenue,
		age_group
from mytable
group by age_group
order by sum(purchase_amount) desc;
    











